### ISSUE TITLE
Support Zip Archive

### ISSUE THREAD

**Issue by L0rD59** [prestaconcept/capistrano-archive#1]
Hi,

Thx for this contribution.

I would like to know if it's possible tu support Zip archive format ?

Thx,

**Comment by dgaussin** [comment]
Hi

I don't think it's possible with the current version. The "tar" usage is hardcoded but it's possible but we can image use a variable to allow zip or tar. Can I know why you need zip?

Thanks

**Comment by L0rD59** [comment]
Hi,

Thx for reply, I need Zip, because my artifact/release is generate by Gitlab-CI.

As far i know, Gitlab-CI generate only Zip Format : 

https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html

> Notes: - Since GitLab 8.2 and GitLab Runner 0.7.0, job artifacts that are created by GitLab Runner are uploaded to GitLab and are downloadable as a single archive (tar.gz) using the GitLab UI. - Starting with GitLab 8.4 and GitLab Runner 1.0, the artifacts archive format changed to ZIP, and it is now possible to browse its contents, with the added ability of downloading the files separately.

Thx,

**Comment by L0rD59** [comment]
no longer need anymore, thx
